### ISSUE TITLE
Incorporacao do PostgresSQl ao Ecossistema

### ISSUE THREAD

**Issue by marlinhares** [pengovbr/mod-sei-pen#457]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Incorporacao do PostgresSQl ao Ecossistema

**Comment by santosleonardo** [comment]
Com o lançamento da [release 3.6.0](https://github.com/pengovbr/mod-sei-pen/releases/tag/3.6.0) foi possível instalar e configurar o módulo em um ambiente com SEI 4.0.12 e PostgreSQL 12.

É possível enviar processos para outro órgão, mas não conseguimos receber no ambiente de homologação.

O SEI apresenta o seguinte erro no log:
`Descrição:
Erro gravando log.

Mensagem:
Erro gravando log.

Trilha de Processamento:
#0 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(88): InfraRN->__call('receberProcedim...', Array)
#1 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(181): ReceberProcedimentoRN->receberProcedimento(191675)
#2 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(399): ProcessarPendenciasRN->receberProcedimento('191675')
#3 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(372): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
#4 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(97): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
#5 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(30): PendenciasTramiteRN->encaminharPendencias(false, false, false)
#6 {main}

Descrição Original:
Exception: 'Warning: /opt/infra/infra_php/InfraPostgreSql.php linha:479.
pg_query(): Query failed: ERROR: current transaction is aborted, commands ignored until end of transaction block
' in /opt/infra/infra_php/Infra.php:246
Stack trace:
#0 [internal function]: infraGerarExcecao(2, 'pg_query(): Que...', '/opt/infra/infr...', 479, Array)
#1 /opt/infra/infra_php/InfraPostgreSql.php(479): pg_query(Resource id #138, 'SELECT NEXTVAL(...')
#2 /opt/infra/infra_php/InfraPostgreSql.php(58): InfraPostgreSql->consultarSql('SELECT NEXTVAL(...')
#3 /opt/infra/infra_php/InfraLog.php(63): InfraPostgreSql->getValorSequencia('seq_infra_log')
#4 /opt/infra/infra_php/InfraRN.php(151): InfraLog->gravarControlado('Descri\xE7\xE3o:Erro...')
#5 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(198): InfraRN->__call('gravar', Array)
#6 /opt/infra/infra_php/InfraRN.php(151): ReceberProcedimentoRN->receberProcedimentoInternoControlado(Object(stdClass))
#7 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(88): InfraRN->__call('receberProcedim...', Array)
#8 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(181): ReceberProcedimentoRN->receberProcedimento(191675)
#9 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(399): ProcessarPendenciasRN->receberProcedimento('191675')
#10 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(372): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
#11 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(97): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
#12 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(30): PendenciasTramiteRN->encaminharPendencias(false, false, false)
#13 {main}

Trilha de Processamento Original:
0 [internal function]: infraGerarExcecao(2, 'pg_query(): Que...', '/opt/infra/infr...', 479, Array)
1 /opt/infra/infra_php/InfraPostgreSql.php(479): pg_query(Resource id 138, 'SELECT NEXTVAL(...')
2 /opt/infra/infra_php/InfraPostgreSql.php(58): InfraPostgreSql->consultarSql('SELECT NEXTVAL(...')
3 /opt/infra/infra_php/InfraLog.php(63): InfraPostgreSql->getValorSequencia('seq_infra_log')
4 /opt/infra/infra_php/InfraRN.php(151): InfraLog->gravarControlado('Descri\xE7\xE3o:Erro...')
5 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(198): InfraRN->__call('gravar', Array)
6 /opt/infra/infra_php/InfraRN.php(151): ReceberProcedimentoRN->receberProcedimentoInternoControlado(Object(stdClass))
7 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(88): InfraRN->__call('receberProcedim...', Array)
8 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(181): ReceberProcedimentoRN->receberProcedimento(191675)
9 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(399): ProcessarPendenciasRN->receberProcedimento('191675')
10 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(372): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
11 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(97): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
12 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(30): PendenciasTramiteRN->encaminharPendencias(false, false, false)
13 {main}`

**Comment by santosleonardo** [comment]
Após observar os logs dos scripts atualização, notei que o módulo não estava sendo instalado corretamente (o ambiente estava na versão [3.3.3](https://github.com/pengovbr/mod-sei-pen/tree/3.3.3)).

Como ainda não estamos na produção, optei remover alguns arquivos e dados do módulo e tentar instalar novamente.

Após esses procedimentos foi possível instalar com sucesso o módulo no SEI 4.0.12 e PostgreSQL 12.

As ações foram bem radicais, como `drop` de todas as sequências e tabelas do módulo e remoção de menus.

Estamos na fase de homologação para prosseguir com a instalação em produção.
