### ISSUE TITLE
Erro ao Atualizar o Módulo para a versão 3.6.2

### ISSUE THREAD

**Issue by yurioliveiramgi** [pengovbr/mod-sei-pen#527]
**Descreva o erro**
Essa issue decorre do chamado Nº 9077880.

Ao atualizar o módulo de integração do SEI com a Plataforma do Tramita GOV.BR, um erro é apresentado.

O erro está relacionado a introdução da variável **EnviarApenasComponentesDigitaisPendentes**. Ainda que, segundo a documentação existente, a referida variável seja opcional e não necessariamente carecia de ser declarada.

Por alguma razão, as versões 3.6.1 e 3.6.2 estão exigindo, ao menos, que a referida variável seja declarada.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Partindo de um ambiente com versão do módulo de integração anterior a 3.3.0 atualize para a versão 3.6.2;
2. Observe o erro no log da Trilha de processamento.

-----

**Comportamento esperado**
Existem duas possibilidades:
1. Que a variável volte a ser opcional
2. Que a variável permaneça obrigatória, contudo seja criado um script que a declare no momento de atualização da versão.

A primeira possibilidade está sendo apontada como a mais viável. Contudo, projetando que o envio parcial possa vir a ser uma funcionalidade raiz do módulo, talvez a adequação dos scripts de atualização ou instalação apresentam-se como uma razoável solução.

-----
**Log de Erros**
Bind:
v1: md_pen_envio_comp_digitais
 
00147 - [InfraOracle->consultarSql] 0 registro(s)
00148 - [InfraOracle->consultarSql] 0 s
00149 - [InfraRN->__call] InfraSequenciaRN.excluir
00150 - [InfraOracle->abrirTransacao] InfraOracle-//[oracle11-seihom.sede.embrapa.br:1594/seihomv4-1594-seihomv4-sei_homv4](http://oracle11-seihom.sede.embrapa.br:1594/seihomv4-1594-seihomv4-sei_homv4)
00151 - [InfraOracle->confirmarTransacao] InfraOracle-//[oracle11-seihom.sede.embrapa.br:1594/seihomv4-1594-seihomv4-sei_homv4](http://oracle11-seihom.sede.embrapa.br:1594/seihomv4-1594-seihomv4-sei_homv4)
Descri��o:
Configura��o EnviarApenasComponentesDigitaisPendentes n�o encontrada no grupo PEN.
 
Mensagem:
Configura��o EnviarApenasComponentesDigitaisPendentes n�o encontrada no grupo PEN.
 
Trilha de Processamento:
#0 /opt/v412/infra/infra_php/InfraScriptVersao.php(237): InfraScript->processarErro('ERRO ATUALIZAND...', Object(InfraException))
#1 /opt/v412/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2823): InfraScriptVersao->atualizarVersao()
#2 {main}
 
Trilha de Processamento Original:
\n0 /opt/v412/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2752): InfraConfiguracao->getValor('PEN', 'EnviarApenasCom...')
\n1 /opt/v412/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(279): PenAtualizarSeiRN->instalarV3060()
\n2 /opt/v412/infra/infra_php/InfraRN.php(149): PenAtualizarSeiRN->atualizarVersaoConectado()
\n3 /opt/v412/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(45): InfraRN->__call('atualizarVersao', Array)
\n4 /opt/v412/infra/infra_php/InfraScriptVersao.php(396): VersaoSei4RN->atualizarVersaoCompatibilidade('3.5.0')
\n5 /opt/v412/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSEI))
\n6 /opt/v412/infra/infra_php/InfraScriptVersao.php(235): InfraRN->__call('atualizarVersao...', Array)
\n7 /opt/v412/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2823): InfraScriptVersao->atualizarVersao()
\n8 {main}

**Comment by yurioliveiramgi** [comment]
Para conhecimento e validação @euviniciusmendonca e @caduvieira .

**Comment by yurioliveiramgi** [comment]
@euviniciusmendonca PSC

**Comment by amelquia** [comment]
22/07/24
Aguardar retorno das férias do @caduvieira no dia 25/07, para validar essa issue juntamente com o time de negócios @yurioliveiramgi  e @euviniciusmendonca .

**Comment by yurioliveiramgi** [comment]
Apenas a nível de atualização:

Um novo chamado 10523987 foi aberto relatando o mesmo problema.

@amelquia , @mateussbh , @euviniciusmendonca , PSC

**Comment by caduvieira** [comment]
Isso é um erro que vai dar com todos que tentarem subir a versão e não tiverem o campo no arquivo de configurações

**Comment by euviniciusmendonca** [comment]
@mateussbh @amelquia @yurioliveiramgi 

Foi realizada uma reunião de alinhamento e foi decidido que a variável ( EnviarApenasComponentesDigitaisPendentes) será obrigatória.

**Comment by caduvieira** [comment]
Sugiro então adicionar uma nota no changelog.

**Comment by amelquia** [comment]
08/08/24 - Daily
Conforme acordado com @mateussbh , essa issue foi validada e será movida para aceite técnico.

**Comment by yurioliveiramgi** [comment]
@mateussbh e @sergioadao , apenas para fins de registro, evidenciar se foram realizados testes de atualização para a versão 3.7.0 a partir de versões anteriores a 3.6.2.

De preferência 3.5.0, alguma versão abaixo da 3.3.0 e outra intermediária.

**Comment by sergioadao** [comment]
Bom dia Yuri......só fiz a partir da 3.5.0......vamos ver com o Mateus como estruturar este teste....


[Brasão da República]   Sérgio Adão da Silva
Especialista em Infraestrutura de Tecnologia da Informação
***@***.***
(61) 2020-2430 / (48) 9 9615-9214
Diretoria de Informações, Serviços e Sistemas de Gestão
Ministério da Gestão e da Inovação em Serviços Públicos
gov.br/gestao<https://gov.br/gestao>
________________________________
De: Yuri Oliveira ***@***.***>
Enviado: segunda-feira, 21 de outubro de 2024 08:59
Para: pengovbr/mod-sei-pen ***@***.***>
Cc: Sergio Adao da Silva ***@***.***>; Mention ***@***.***>
Assunto: Re: [pengovbr/mod-sei-pen] Erro ao Atualizar o Módulo para a versão 3.6.2 (Issue #527)


@mateussbh<http://antispam.economia.gov.br/mailinspector/tap/WarningUrlPage.php?HSCTYPE=0&HSCRULE=2&HSCID=NTc0RThCRDUxOEQuQTZCM0I=
&HSCMLICHECKID0005=578cd9fe7235003ee50041a0c2841678&URLCHECKHSCMLI09132012warnning=H4sIAAAAAAAAA8soKSkottLXT88syShN0kvOz9XPTSxJLS0uTsoAABbHV6McAAAA> e @sergioadao<http://antispam.economia.gov.br/mailinspector/tap/WarningUrlPage.php?HSCTYPE=0&HSCRULE=2&HSCID=NTc0RThCRDUxOEQuQTZCM0I=
&HSCMLICHECKID0005=578cd9fe7235003ee50041a0c2841678&URLCHECKHSCMLI09132012warnning=H4sIAAAAAAAAA8soKSkottLXT88syShN0kvOz9UvTi1Kz8xPTEnMBwCnaVgwHQAAAA==> , apenas para fins de registro, evidenciar se foram realizados testes de atualização para a versão 3.7.0 a partir de versões anteriores a 3.6.2.

De preferência 3.5.0, alguma versão abaixo da 3.3.0 e outra intermediária.

—
Reply to this email directly, view it on GitHub<http://antispam.economia.gov.br/mailinspector/tap/WarningUrlPage.php?HSCTYPE=0&HSCRULE=2&HSCID=NTc0RThCRDUxOEQuQTZCM0I=
&HSCMLICHECKID0005=578cd9fe7235003ee50041a0c2841678&URLCHECKHSCMLI09132012warnning=H4sIAAAAAAAAA8soKSkottLXT88syShN0kvOz9UvSM1Lzy9LKtLPzU/RLU7N1AUK6GcWF5emFuub
Gpkrg5lAhbmpeSW6RiZGZibmBgYWJgCFLXbISgAAAA==>, or unsubscribe<http://antispam.economia.gov.br/mailinspector/tap/WarningUrlPage.php?HSCTYPE=0&HSCRULE=2&HSCID=NTc0RThCRDUxOEQuQTZCM0I=
&HSCMLICHECKID0005=578cd9fe7235003ee50041a0c2841678&URLCHECKHSCMLI09132012warnning=H4sIAAAAAAAAAxXB0Q6CIBQA0C8qNtHcekNdanBVBAF9U1fJQ9oC/r91zub9x10Relm/heW8Hm+0
H94+7Tp7e+wOhd2Fxa1fuzxOc/AbIkOSAiOloaaP2wSAdmqkbIrlUNyJypubgAv5y2iVjqLPVVVH
hQDFdW0wAxXjVjDZNpGmHHeN0ppiOVQwFTX0uuRYEsjGkv8A+hnK3ZwAAAA=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/pengovbr/mod-sei-pen/issues/527#issuecomment-2426470084", "url": "https://github.com/pengovbr/mod-sei-pen/issues/527#issuecomment-2426470084", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by yurioliveiramgi** [comment]
@caduvieira e @mateussbh , essa também foi contemplada na 3.7.0, certo? Como é uma questão técnica, se puderem, concluam e movam o status para concluído. 
Obrigado.
