### ISSUE TITLE
Erro na atualização da versão 3.5.0 para a versão 3.6.1

### ISSUE THREAD

**Issue by dudamark** [pengovbr/mod-sei-pen#541]
**Descreva o erro**
Está ocorrendo erro na atualização da versão 3.5.0 para a versão 3.6.1.
Descrevo abaixo os logs de erro do InfraLog.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]
 - Banco de dados: [MySQL, SQLServer, Oracle ou PostgreSQL]
-----
Base de dados: MySQL 8.0
**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Descrição:
Duplicate entry 'pen_map_hipotese_legal_recebimento_listar-100000100' for key 'recurso.ak_recurso_nome'

Mensagem:
Duplicate entry 'pen_map_hipotese_legal_recebimento_listar-100000100' for key 'recurso.ak_recurso_nome'

Trilha de Processamento:
#0 /opt/infra/infra_php/InfraScriptVersao.php(237): InfraScript->processarErro('ERRO ATUALIZAND...', Object(InfraException))
#1 /opt/sip/scripts/mod-pen/sip_atualizar_versao_modulo_pen.php(2156): InfraScriptVersao->atualizarVersao()
#2 {main}

Detalhes:
UPDATE recurso SET nome=?,caminho=? WHERE recurso.id_recurso=?

Bind:
0: s, pen_map_hipotese_legal_recebimento_listar
1: s, controlador.php?acao=pen_map_hipotese_legal_recebimento_listar
2: i, 100015718

Trilha de Processamento Original:
0 /opt/infra/infra_php/InfraBD.php(210): InfraMySqli->executarSql('UPDATE recurso ...', Array)
1 /opt/sip/scripts/mod-pen/sip_atualizar_versao_modulo_pen.php(969): InfraBD->alterar(Object(RecursoDTO))
2 /opt/sip/scripts/mod-pen/sip_atualizar_versao_modulo_pen.php(129): PenAtualizarSipRN->instalarV103()
3 /opt/infra/infra_php/InfraRN.php(149): PenAtualizarSipRN->atualizarVersaoConectado()
4 /opt/sip/scripts/mod-pen/sip_atualizar_versao_modulo_pen.php(48): InfraRN->__call('atualizarVersao', Array)
5 /opt/infra/infra_php/InfraScriptVersao.php(396): VersaoSip4RN->atualizarVersaoCompatibilidade('0.0.0')
6 /opt/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSip))
7 /opt/infra/infra_php/InfraScriptVersao.php(235): InfraRN->__call('atualizarVersao...', Array)
8 /opt/sip/scripts/mod-pen/sip_atualizar_versao_modulo_pen.php(2156): InfraScriptVersao->atualizarVersao()
9 {main}

Descrição:
Configuração EnviarApenasComponentesDigitaisPendentes não encontrada no grupo PEN.

Mensagem:
Configuração EnviarApenasComponentesDigitaisPendentes não encontrada no grupo PEN.

Trilha de Processamento:
#0 /opt/infra/infra_php/InfraScriptVersao.php(237): InfraScript->processarErro('ERRO ATUALIZAND...', Object(InfraException))
#1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2823): InfraScriptVersao->atualizarVersao()
#2 {main}

Trilha de Processamento Original:
0 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2752): InfraConfiguracao->getValor('PEN', 'EnviarApenasCom...')
1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(279): PenAtualizarSeiRN->instalarV3060()
2 /opt/infra/infra_php/InfraRN.php(149): PenAtualizarSeiRN->atualizarVersaoConectado()
3 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(45): InfraRN->__call('atualizarVersao', Array)
4 /opt/infra/infra_php/InfraScriptVersao.php(396): VersaoSei4RN->atualizarVersaoCompatibilidade('3.5.0')
5 /opt/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSEI))
6 /opt/infra/infra_php/InfraScriptVersao.php(235): InfraRN->__call('atualizarVersao...', Array)
7 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2823): InfraScriptVersao->atualizarVersao()
8 {main}

**Comment by caduvieira** [comment]
Adicione a variável 'EnviarApenasComponentesDigitaisPendentes' no seu arquivo de configuração do Módulo. Veja p arquivo exemplo se desejar. Refs #527
