### ISSUE TITLE
Falha ao instalar release/3.7.0

### ISSUE THREAD

**Issue by marlinhares** [pengovbr/mod-sei-pen#551]
**Descreva o erro**
Em uma base zerada do SEI está dando erro ao instalar o modulo do zero.
branch: release/3.7.0
sei: 4.0.12.15; 4.1.1, 4.1.2, 4.1.3
base mysql

Ao rodar o script /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php

```
06954 - [InfraMySqli->consultarSql] SELECT
bp.id_protocolo, rel.id_andamento, rel.id_atividade_expedicao, rel.tentativas
FROM md_pen_bloco_protocolo bp
inner join md_pen_rel_expedir_lote rel on rel.id_procedimento = bp.id_protocolo
06955 - [InfraMySqli->consultarSql] 0 registro(s)
06956 - [InfraMySqli->consultarSql] 0,003 s
06957 - [InfraRN->__call] TramiteEmBlocoRN.listar
06958 - [InfraMySqli->consultarSql] SELECT md_pen_bloco.id_unidade AS idunidade,md_pen_bloco.id,md_pen_bloco.id_usuario AS idusuario,md_pen_bloco.descricao,md_pen_bloco.idx_bloco AS idxbloco,md_pen_bloco.sta_tipo AS statipo,md_pen_bloco.sta_estado AS staestado,md_pen_bloco.ordem FROM md_pen_bloco WHERE md_pen_bloco.id_unidade IS NOT NULL
06959 - [InfraMySqli->consultarSql] 0 registro(s)
06960 - [InfraMySqli->consultarSql] 0,003 s
06961 - [Infra->infraGerarExcecao] 20: Notice: /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php linha:2950.
Undefined variable: arrObjTramiteEmBloco
06962 - [Infra->infraGerarExcecao] 10: Warning: /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php linha:2950.
Invalid argument supplied for foreach()
Descri��o:
Erro atualizando VERSAO: Exception: 'Warning: /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php linha:2950.
Invalid argument supplied for foreach()
' in /opt/infra/infra_php/Infra.php:264
Stack trace:
#0 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2950): infraGerarExcecao(2, 'Invalid argumen...', '/opt/sei/script...', 2950, Array)
#1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(285): PenAtualizarSeiRN->instalarV3070()
#2 /opt/infra/infra_php/InfraRN.php(149): PenAtualizarSeiRN->atualizarVersaoConectado()
#3 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(45): InfraRN->__call('atualizarVersao', Array)
#4 /opt/infra/infra_php/InfraScriptVersao.php(396): VersaoSei4RN->atualizarVersaoCompatibilidade('0.0.0')
#5 /opt/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSEI))
#6 /opt/infra/infra_php/InfraScriptVersao.php(235): InfraRN->__call('atualizarVersao...', Array)
#7 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(3080): InfraScriptVersao->atualizarVersao()
#8 {main}
Mensagem:
Erro atualizando VERSAO: Exception: 'Warning: /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php linha:2950.
Invalid argument supplied for foreach()
' in /opt/infra/infra_php/Infra.php:264
Stack trace:
#0 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2950): infraGerarExcecao(2, 'Invalid argumen...', '/opt/sei/script...', 2950, Array)
#1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(285): PenAtualizarSeiRN->instalarV3070()
#2 /opt/infra/infra_php/InfraRN.php(149): PenAtualizarSeiRN->atualizarVersaoConectado()
#3 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(45): InfraRN->__call('atualizarVersao', Array)
#4 /opt/infra/infra_php/InfraScriptVersao.php(396): VersaoSei4RN->atualizarVersaoCompatibilidade('0.0.0')
#5 /opt/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSEI))
#6 /opt/infra/infra_php/InfraScriptVersao.php(235): InfraRN->__call('atualizarVersao...', Array)
#7 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(3080): InfraScriptVersao->atualizarVersao()
#8 {main}
Trilha de Processamento:
#0 /opt/infra/infra_php/InfraScriptVersao.php(237): InfraScript->processarErro('ERRO ATUALIZAND...', Object(InfraException))
#1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(3080): InfraScriptVersao->atualizarVersao()
#2 {main}
Descri��o Original:
Exception: 'Warning: /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php linha:2950.
Invalid argument supplied for foreach()
' in /opt/infra/infra_php/Infra.php:264
Stack trace:
#0 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2950): infraGerarExcecao(2, 'Invalid argumen...', '/opt/sei/script...', 2950, Array)
#1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(285): PenAtualizarSeiRN->instalarV3070()
#2 /opt/infra/infra_php/InfraRN.php(149): PenAtualizarSeiRN->atualizarVersaoConectado()
#3 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(45): InfraRN->__call('atualizarVersao', Array)
#4 /opt/infra/infra_php/InfraScriptVersao.php(396): VersaoSei4RN->atualizarVersaoCompatibilidade('0.0.0')
#5 /opt/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSEI))
#6 /opt/infra/infra_php/InfraScriptVersao.php(235): InfraRN->__call('atualizarVersao...', Array)
#7 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(3080): InfraScriptVersao->atualizarVersao()
#8 {main}
Trilha de Processamento Original:
\n0 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2950): infraGerarExcecao(2, 'Invalid argumen...', '/opt/sei/script...', 2950, Array)
\n1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(285): PenAtualizarSeiRN->instalarV3070()
\n2 /opt/infra/infra_php/InfraRN.php(149): PenAtualizarSeiRN->atualizarVersaoConectado()
\n3 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(45): InfraRN->__call('atualizarVersao', Array)
\n4 /opt/infra/infra_php/InfraScriptVersao.php(396): VersaoSei4RN->atualizarVersaoCompatibilidade('0.0.0')
\n5 /opt/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSEI))
\n6 /opt/infra/infra_php/InfraScriptVersao.php(235): InfraRN->__call('atualizarVersao...', Array)
\n7 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(3080): InfraScriptVersao->atualizarVersao()
\n8 {main}
```

Dúvidas avisar

**Comment by yurioliveiramgi** [comment]
Problema resolvido. Issue concluída.
