### ISSUE TITLE
Falha no recebimento de recibo de trâmite de envio

### ISSUE THREAD

**Issue by yodog** [pengovbr/mod-sei-pen#575]
ao fazer o envio de um determinado processo apos o envio dos metadados e dos componentes digitais estamos obtendo essa exceçao no processo de expedir procedimento.

como podemos descobrir qual componente digital nao esta sendo enviado?

> Falha na obtenção do recibo de envio de protocolo do trâmite nnnnnnn. Falha no recebimento de recibo de trâmite de envio. Descrição:
> 
> SoapFault exception: [SOAP-ENV:Server] TrÃ¢mite com idt, n.nnn.nnn, ainda nÃ£o recebeu todos os componentes digitais in /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php:1649
> Stack trace:
> #0 /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(1649): SoapClient->__call('receberReciboDe...', Array)
> #1 /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(1944): ProcessoEletronicoRN->{closure}(Object(BeSimple\SoapClient\SoapClient))
> #2 /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(1650): ProcessoEletronicoRN->tentarNovamenteSobErroHTTP(Object(Closure))
> #3 /opt/sei/web/modulos/pen/rn/ExpedirProcedimentoRN.php(2903): ProcessoEletronicoRN->receberReciboDeEnvio(nnnnnnn)
> #4 /opt/infra/infra_php/InfraRN.php(151): ExpedirProcedimentoRN->receberReciboDeEnvioControlado(nnnnnnn)
> #5 /opt/sei/web/modulos/pen/rn/ExpedirProcedimentoRN.php(297): InfraRN->__call('receberReciboDe...', Array)
> #6 /opt/infra/infra_php/InfraRN.php(151): ExpedirProcedimentoRN->expedirProcedimentoControlado(Object(ExpedirProcedimentoDTO))
> #7 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(309): InfraRN->__call('expedirProcedim...', Array)
> #8 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(354): ProcessarPendenciasRN->expedirLote('1443657')
> #9 [internal function]: ProcessarPendenciasRN->{closure}(Object(GearmanJob), NULL)
> #10 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(89): GearmanWorker->work()
> #11 /opt/sei/scripts/mod-pen/ProcessamentoTarefasPEN.php(34): ProcessarPendenciasRN->processarPendencias()
> #12 /opt/sei/scripts/mod-pen/ProcessamentoTarefasPEN.php(47): ProcessamentoTarefasPEN->processarPendencias()
> #13 {main}
> 
> Mensagem:
> TrÃ¢mite com idt, n.nnn.nnn, ainda nÃ£o recebeu todos os componentes digitais
> 
> Trilha de Processamento:
> #0 /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(1649): SoapClient->__call('receberReciboDe...', Array)
> #1 /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(1944): ProcessoEletronicoRN->{closure}(Object(BeSimple\SoapClient\SoapClient))
> #2 /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(1650): ProcessoEletronicoRN->tentarNovamenteSobErroHTTP(Object(Closure))
> #3 /opt/sei/web/modulos/pen/rn/ExpedirProcedimentoRN.php(2903): ProcessoEletronicoRN->receberReciboDeEnvio(nnnnnnn)
> #4 /opt/infra/infra_php/InfraRN.php(151): ExpedirProcedimentoRN->receberReciboDeEnvioControlado(nnnnnnn)
> #5 /opt/sei/web/modulos/pen/rn/ExpedirProcedimentoRN.php(297): InfraRN->__call('receberReciboDe...', Array)
> #6 /opt/infra/infra_php/InfraRN.php(151): ExpedirProcedimentoRN->expedirProcedimentoControlado(Object(ExpedirProcedimentoDTO))
> #7 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(309): InfraRN->__call('expedirProcedim...', Array)
> #8 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(354): ProcessarPendenciasRN->expedirLote('1443657')
> #9 [internal function]: ProcessarPendenciasRN->{closure}(Object(GearmanJob), NULL)
> #10 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(89): GearmanWorker->work()
> #11 /opt/sei/scripts/mod-pen/ProcessamentoTarefasPEN.php(34): ProcessarPendenciasRN->processarPendencias()
> #12 /opt/sei/scripts/mod-pen/ProcessamentoTarefasPEN.php(47): ProcessamentoTarefasPEN->processarPendencias()
> #13 {main}
>

**Comment by yodog** [comment]
percebi que havia dois documentos com o mesmo hash no processo. ao excluir um deles o envio finalizou.

bug ou feature?

**Comment by yurioliveiramgi** [comment]
@mateussbh tenho memória de discutirmos algo parecido. Consegue me confirmar se foi resolvido?

@amelquia , PSC.
